// <auto-generated />
using System;
using InvoicesWebService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InvoicesWebService.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260510123412_WebService")]
    partial class WebService
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shared.Entities.DepartmentAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_department_access_user");

                    b.HasIndex("UserId", "DepartmentId")
                        .IsUnique()
                        .HasDatabaseName("UX_department_access_user_dept");

                    b.ToTable("department_access", (string)null);
                });

            modelBuilder.Entity("Shared.Entities.DraftInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregationGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency_code");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<decimal>("NdsRate")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("nds_rate");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalNdsAmount")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("total_nds_amount");

                    b.Property<decimal>("TotalWithNds")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("total_with_nds");

                    b.Property<decimal>("TotalWithoutNds")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValidationError")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("validation_error");

                    b.HasKey("Id");

                    b.HasIndex("AggregationGroupId")
                        .IsUnique()
                        .HasDatabaseName("UX_draft_invoice_group_id");

                    b.ToTable("draft_invoice", (string)null);
                });

            modelBuilder.Entity("Shared.Entities.DraftInvoiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountWithoutNds")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("amount_without_nds");

                    b.Property<Guid>("DraftInvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("draft_invoice_id");

                    b.Property<decimal>("NdsAmount")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("nds_amount");

                    b.Property<decimal>("NdsRate")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("nds_rate");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("product_code");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("product_name");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("quantity");

                    b.Property<Guid?>("RawTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("raw_transaction_id");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("total_amount");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("unit");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("DraftInvoiceId")
                        .HasDatabaseName("IX_draft_invoice_line_draft");

                    b.HasIndex("RawTransactionId")
                        .IsUnique()
                        .HasDatabaseName("UX_draft_invoice_line_raw_tx");

                    b.ToTable("draft_invoice_line", (string)null);
                });

            modelBuilder.Entity("Shared.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CurrentVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("current_version");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<Guid?>("DraftInvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("draft_invoice_id");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issue_date");

                    b.Property<Guid?>("LastAuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_author_id");

                    b.Property<decimal>("NdsRate")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("nds_rate");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("number");

                    b.Property<DateTime?>("PaymentDocDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_doc_date");

                    b.Property<string>("PaymentDocNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("payment_doc_number");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("SequenceNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sequence_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalNds")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("total_nds");

                    b.Property<decimal>("TotalWithNds")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("total_with_nds");

                    b.Property<decimal>("TotalWithoutNds")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DraftInvoiceId")
                        .IsUnique()
                        .HasDatabaseName("UX_invoice_draft_id");

                    b.HasIndex("LastAuthorId");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("UX_invoice_number");

                    b.HasIndex("Status", "IssueDate")
                        .HasDatabaseName("IX_invoice_status_date");

                    b.ToTable("invoice", (string)null);
                });

            modelBuilder.Entity("Shared.Entities.InvoiceFieldChangeHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ChangedById")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("field_name");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("old_value");

                    b.HasKey("Id");

                    b.HasIndex("ChangedById");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("IX_invoice_change_history_invoice");

                    b.ToTable("invoice_field_change_history", (string)null);
                });

            modelBuilder.Entity("Shared.Entities.InvoiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountWithNds")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("amount_with_nds");

                    b.Property<decimal>("AmountWithoutNds")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("amount_without_nds");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<decimal>("NdsAmount")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("nds_amount");

                    b.Property<decimal>("NdsRate")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("nds_rate");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("product_code");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("product_name");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("total_amount");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("unit");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("IX_invoice_line_invoice");

                    b.ToTable("invoice_line", (string)null);
                });
            
            modelBuilder.Entity("Shared.Entities.DraftInvoiceLine", b =>
                {
                    b.HasOne("Shared.Entities.DraftInvoice", "DraftInvoice")
                        .WithMany("Lines")
                        .HasForeignKey("DraftInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DraftInvoice");
                });

            modelBuilder.Entity("Shared.Entities.Invoice", b =>
                {
                    b.HasOne("Shared.Entities.DraftInvoice", null)
                        .WithMany()
                        .HasForeignKey("DraftInvoiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Shared.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("LastAuthorId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Shared.Entities.InvoiceFieldChangeHistory", b =>
                {
                    b.HasOne("Shared.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Shared.Entities.Invoice", null)
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shared.Entities.InvoiceLine", b =>
                {
                    b.HasOne("Shared.Entities.Invoice", "Invoice")
                        .WithMany("Lines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Shared.Entities.DraftInvoice", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Shared.Entities.Invoice", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
