// <auto-generated />
using System;
using AbsIntegrationService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AbsIntegrationService.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260510122648_IntegrationService")]
    partial class IntegrationService
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shared.Entities.AggregationGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AdvanceCount")
                        .HasColumnType("integer")
                        .HasColumnName("advance_count");

                    b.Property<int>("CorrectiveCount")
                        .HasColumnType("integer")
                        .HasColumnName("corrective_count");

                    b.Property<Guid?>("CounterpartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("counterparty_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<DateTime?>("LastProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_processed_at");

                    b.Property<string>("OperationNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("operation_number");

                    b.Property<DateTime?>("ReadyAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ready_at");

                    b.Property<int>("ShipmentCount")
                        .HasColumnType("integer")
                        .HasColumnName("shipment_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_count");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValidationError")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("validation_error");

                    b.HasKey("Id");

                    b.HasIndex("CounterpartyId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("OperationNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_aggregation_group_drf");

                    b.HasIndex("Status", "TransactionDate")
                        .HasDatabaseName("IX_aggregation_group_status_date");

                    b.ToTable("aggregation_group", "public");
                });

            modelBuilder.Entity("Shared.Entities.Counterparty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Inn")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("inn");

                    b.Property<string>("Kpp")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kpp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Inn")
                        .HasDatabaseName("IX_counterparty_inn");

                    b.ToTable("counterparty", "public");
                });

            modelBuilder.Entity("Shared.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_department_code");

                    b.ToTable("department", "public");
                });

            modelBuilder.Entity("Shared.Entities.ProcessingError", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AggregationGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregation_group_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DraftInvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("draft_invoice_id");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid?>("RawTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("raw_transaction_id");

                    b.Property<bool>("Resolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("resolved");

                    b.Property<bool>("Retryable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("retryable");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("stage");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AggregationGroupId");

                    b.HasIndex("RawTransactionId");

                    b.HasIndex("Resolved", "Retryable", "CreatedAt")
                        .HasDatabaseName("IX_processing_error_retries");

                    b.ToTable("processing_error", "public");
                });

            modelBuilder.Entity("Shared.Entities.RawTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AggregationGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregation_group_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("amount");

                    b.Property<Guid?>("CounterpartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("counterparty_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("currency_code");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<decimal>("NdsAmount")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("nds_amount");

                    b.Property<decimal>("NdsRate")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("nds_rate");

                    b.Property<string>("OperationNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("operation_number");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payload_hash");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_code");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("product_name");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("quantity");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.Property<string>("UnitMeasure")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("unit_measure");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)")
                        .HasColumnName("unit_price");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValidationError")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("validation_error");

                    b.HasKey("Id");

                    b.HasIndex("AggregationGroupId");

                    b.HasIndex("CounterpartyId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PayloadHash")
                        .IsUnique()
                        .HasDatabaseName("UX_rawtransaction_payload_hash");

                    b.HasIndex("OperationNumber", "Type")
                        .HasDatabaseName("IX_rawtransaction_drf_type");

                    b.HasIndex("Status", "ReceivedAt")
                        .HasDatabaseName("IX_rawtransaction_status_received");

                    b.ToTable("raw_transaction", "public");
                });

            modelBuilder.Entity("Shared.Entities.AggregationGroup", b =>
                {
                    b.HasOne("Shared.Entities.Counterparty", null)
                        .WithMany()
                        .HasForeignKey("CounterpartyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Shared.Entities.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Shared.Entities.ProcessingError", b =>
                {
                    b.HasOne("Shared.Entities.AggregationGroup", null)
                        .WithMany()
                        .HasForeignKey("AggregationGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Shared.Entities.RawTransaction", null)
                        .WithMany()
                        .HasForeignKey("RawTransactionId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Shared.Entities.RawTransaction", b =>
                {
                    b.HasOne("Shared.Entities.AggregationGroup", null)
                        .WithMany()
                        .HasForeignKey("AggregationGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Shared.Entities.Counterparty", null)
                        .WithMany()
                        .HasForeignKey("CounterpartyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Shared.Entities.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
