name: invoices-system

services:
    # ====================== БАЗЫ ДАННЫХ ======================
    postgres:
      image: postgres:16-alpine
      container_name: postgres-main
      environment:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
      ports:
        - "5432:5432"
      volumes:
        - postgres-data:/var/lib/postgresql/data
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres -d invoices_db" ]
        interval: 10s
        timeout: 5s
        retries: 5
     # ====================== KAFKA ======================
    kafka:
      container_name: kafka-abs
      image: apache/kafka:latest
      ports:
        - "9092:9092" #docker
        - "9094:9094" #host machine
      environment:
        KAFKA_NODE_ID: 1
        KAFKA_CLUSTER_ID: "invoices-alfa-cluster-1"
        KAFKA_PROCESS_ROLES: 'broker, controller'
        
        KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
        KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
        
        KAFKA_LISTENERS: >
          PLAINTEXT://0.0.0.0:9092,
          EXTERNAL://0.0.0.0:9094,
          CONTROLLER://0.0.0.0:9093
        KAFKA_ADVERTISED_LISTENERS: >
          PLAINTEXT://kafka:9092,
          EXTERNAL://localhost:9094
        
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
          CONTROLLER:PLAINTEXT,
          PLAINTEXT:PLAINTEXT,
          EXTERNAL:PLAINTEXT
        
        KAFKA_INNER_BROKER_LISTENER_NAME: 'PLAINTEXT'
        
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        KAFKA_AUTO_CREATE_TOPIC_ENABLE: 'true'
        
        KAFKA_NUM_PARTITIONS: 12
        
        KAFKA_LOG_DIRS: /var/lib/kafka/data
      volumes:
        - kafka_data:/var/lib/kafka/data
      healthcheck:
        test: [ "CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/9092' || exit 1" ]
        interval: 5s
        timeout: 5s
        retries: 10
        start_period: 40s
    
    kafka-ui:
      container_name: kafka-ui
      image: ghcr.io/kafbat/kafka-ui:latest
      ports:
        - "8070:8080"
      depends_on:
        - kafka
      environment:
        KAFKA_CLUSTERS_0_NAME: local
        KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
        DYNAMIC_CONFIG_ENABLED: 'true'
      restart: unless-stopped
  
  # ====================== МЕТРИКИ ====================== 
    prometheus:
      image: prom/prometheus:v2.52.0
      container_name: prometheus
      command:
        - "--config.file=/etc/prometheus/prometheus.yml"
        - "--storage.tsdb.path=/prometheus"
        - "--storage.tsdb.retention.time=15d"
        - "--web.enable-lifecycle"
        - "--web.enable-admin-api"
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
        - prometheus-data:/var/lib/prometheus
      ports:
        - "9090:9090"
      networks:
        - monitoring
      restart: unless-stopped
      mem_limit: 1g
      cpus: 1.5

    tempo:
      image: grafana/tempo:2.5.0
      container_name: tempo
      command: ["-config.file=/etc/tempo/config.yaml"]
      volumes:
        - ./tempo.yaml:/etc/tempo/config.yaml:ro
        - tempo-data:/var/lib/tempo
      ports:
        - "3200:3200"
      networks:
        - monitoring
      restart: unless-stopped
      mem_limit: 512m
      cpus: 0.5

    cadvisor:
      image: gcr.io/cadvisor/cadvisor:v0.49.1
      container_name: cadvisor
      privileged: true
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:ro
        - /sys:/sys:ro
        - /var/lib/docker:/var/lib/docker:ro
      ports:
        - "8082:8082"
      networks:
        - monitoring
      restart: unless-stopped
      mem_limit: 256m

    grafana:
      image: grafana/grafana:10.4.0
      container_name: grafana
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=admin
        - GF_USERS_ALLOW_SIGN_UP=false
      volumes:
        - grafana-data:/var/lib/grafana
      ports:
        - "3000:3000"
      networks:
        - monitoring
      depends_on:
        - prometheus
        - tempo
      restart: unless-stopped
    
  # ====================== МИКРОСЕРВИСЫ ======================
    abs-integration-service:
      build:
        context: ../AbsIntegrationService
        dockerfile: Dockerfile
      container_name: abs-integration-service
      depends_on:
        postgres:
          condition: service_healthy
        kafka:
          condition: service_healthy
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - OTEL_SERVICE_NAME=abs-ingestion-service
      networks:
        - monitoring
        - default
      ports:
        - "5001:8080"
      restart: unless-stopped
      
    web-invoice-service:
      build:
        context: ../InvoicesWebService
        dockerfile: Dockerfile
      container_name: invoice-service
      depends_on:
        postgres:
          condition: service_healthy
        kafka:
          condition: service_healthy
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - OTEL_SERVICE_NAME=web-invoice-service
      networks:
        - monitoring
        - default
      ports:
        - "5002:8081"
      restart: unless-stopped

networks:
  monitoring:
    driver: bridge

volumes:
  postgres-data:
  kafka_data:
  prometheus-data:
  tempo-data:
  grafana-data:

      
